#!/bin/bash
# Author: Paulo Jeronimo (email: paulojeronimo@gmail.com; twitter: @paulojeronimo)
set +x

CONFIG="$AMBIENTE_HOME"/.projetos
source "$CONFIG" &> /dev/null || {
    cat > "$CONFIG" <<EOF
app=http://github.com/pensandoodireito/sislegis-app
app_frontend=http://github.com/pensandoodireito/sislegis-app-frontend
site=http://github.com/pensandoodireito/sislegis-site
EOF
    source "$CONFIG"
}

[ ! -d ~/projetos -a ! -L ~/projetos ] && {
    cd
    if [[ ${PROJETOS_DIR##~/} =~ ^/.* ]]
    then
        ln -s "$PROJETOS_DIR"
    else
        ln -s "${PROJETOS_DIR##~/}" ${PROJETOS_DIR##*/}
    fi
}

mkdir -p "$PROJETOS_DIR"
cd "$PROJETOS_DIR" || exit $?

SCRIPT=`basename "$0"`
case "$SCRIPT" in
    baixar-*)
        PROJETO=`echo -n ${SCRIPT#baixar-}`;;
esac
if [ "$PROJETO" = "projeto" ]
then
    PROJETO=$1; [ "$PROJETO" ] || { echo "Projeto não informado!"; exit 1; }
fi
rm -rf $PROJETO

git clone ${!PROJETO} $PROJETO || exit $?

if [ "$APP_AMBIENTE" = "homologacao" ]
then
    case "$PROJETO" in
        app)
            sed -i "s,localhost:8080,$APP_IP,g" "$PROJETO/src/main/webapp/WEB-INF/keycloak.json"
            ;;
        app_frontend)
            cd "$PROJETO"
            for f in index.html keycloak.json
            do
                sed -i "s,localhost:8080,$APP_IP,g" $f
            done
            sed -i "s,sislegis.local:8080,$APP_HOST,g" scripts/app.js
            match="localhost:8080" change="$APP_IP" .scripts/change-rest-endpoint.sh
            cd - &> /dev/null
            ;;
    esac
fi

# vim: set ts=4 sw=4 expandtab:
