#!/bin/bash
# Author: Paulo Jeronimo (email: paulojeronimo@gmail.com; twitter: @paulojeronimo)
set +x

CONFIG=~/.projetos

source "$CONFIG" &> /dev/null || {
    echo "O arquivo \"$CONFIG\" não foi encontrado ou está mal configurado!"
    exit 1
}

[ ! -d ~/projetos -a ! -L ~/projetos ] && {
    cd
    if [[ ${PROJETOS_DIR##~/} =~ ^/.* ]]
    then
        ln -s "$PROJETOS_DIR"
    else
        ln -s "${PROJETOS_DIR##~/}" ${PROJETOS_DIR##*/}
    fi
}

mkdir -p "$PROJETOS_DIR"
cd "$PROJETOS_DIR" || exit $?

SCRIPT=`basename "$0"`
case "$SCRIPT" in
    baixar-*)
        PROJETO=`echo -n ${SCRIPT#baixar-}`;;
esac
if [ "$PROJETO" = "projeto" ]
then
    PROJETO=$1; [ "$PROJETO" ] || { echo "Projeto não informado!"; exit 1; }
fi
rm -rf $PROJETO

git clone ${!PROJETO} $PROJETO || exit $?

# vim: set ts=4 sw=4 expandtab:
