#!/bin/bash

OP=${OP:-export}

case "$OP" in
    export) 
        $JBOSS_HOME/bin/standalone.sh \
            -Dkeycloak.migration.action=export \
            -Dkeycloak.migration.provider=dir \
            -Dkeycloak.migration.dir="$CONFIGURACOES_DIR"/keycloak \
            -Dkeycloak.migration.realmName=sislegis \
            -Dkeycloak.migration.usersExportStrategy=REALM_FILE
        ;;
    import)
        $JBOSS_HOME/bin/standalone.sh \
            -Dkeycloak.migration.action=import \
            -Dkeycloak.migration.provider=singleFile \
            -Dkeycloak.migration.file="$CONFIGURACOES_DIR"/keycloak/sislegis-realm.json \
            -Dkeycloak.migration.strategy=OVERWRITE_EXISTING
        ;;
esac
